efs/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    ]

portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('misc_list', views.misc_list, name='misc_list'),
    path('misc/create/', views.misc_new, name='misc_new'),
    path('misc/<int:pk>/edit/', views.misc_edit, name='misc_edit'),
    path('misc/<int:pk>/delete/', views.misc_delete, name='misc_delete'),
    path('asset_list', views.asset_list, name='asset_list'),
    path('asset/create/', views.asset_new, name='asset_new'),
    path('asset/<int:pk>/edit/', views.asset_edit, name='asset_edit'),
    path('asset/<int:pk>/delete/', views.asset_delete, name='asset_delete'),
    url(r'^customers_json/', views.CustomerList.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Asset(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='assets')
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    serial_number = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(default=timezone.now)
    created_date = models.DateTimeField(
        default=timezone.now)

    def created(self):
        self.date = timezone.now()
        self.save()

    def updated(self):
        self.date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

class Misc(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='miscs')
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    date = models.DateField(default=timezone.now)
    created_date = models.DateTimeField(
        default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

portfolio/forms.py
from django import forms
from .models import Customer, Misc, Asset

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)

class MiscForm(forms.ModelForm):
   class Meta:
       model = Misc
       fields = ('customer', 'make', 'model', 'name', 'value', 'category', 'description', 'date',)

class AssetForm(forms.ModelForm):
   class Meta:
       model = Asset
       fields = ('customer', 'make', 'model', 'serial_number', 'category', 'description', 'value', 'date',)

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer


# Create your views here.
now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})

@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')

@login_required
def misc_list(request):
   miscs = misc.objects.filter(created_date__lte=timezone.now())
   return render(request, 'portfolio/misc_list.html', {'miscs': miscs})

@login_required
def misc_new(request):
   if request.method == "POST":
       form = MiscForm(request.POST)
       if form.is_valid():
           misc = form.save(commit=False)
           misc.created_date = timezone.now()
           misc.save()
           misc = misc.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/misc_list.html',
                         {'miscs': misc})
   else:
       form = MiscForm()
       # print("Else")
   return render(request, 'portfolio/misc_new.html', {'form': form})

@login_required
def misc_edit(request, pk):
   misc = get_object_or_404(Misc, pk=pk)
   if request.method == "POST":
       form = MiscForm(request.POST, instance=misc)
       if form.is_valid():
           misc = form.save()
           misc.updated_date = timezone.now()
           misc.save()
           misc = misc.objects.filter(date=timezone.now())
           return render(request, 'portfolio/misc_list.html', {'misc': misc})
   else:
       # print("else")
       form = MiscForm(instance=misc)
   return render(request, 'portfolio/misc_edit.html', {'form': form})

@login_required
def misc_delete(request, pk):
   misc = get_object_or_404(Misc, pk=pk)
   misc.delete()
   return redirect('portfolio:misc_list')

@login_required
def asset_list(request):
    asset = asset.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/asset_list.html',
                 {'assets': asset})

@login_required
def asset_new(request):
   if request.method == "POST":
       form = assetForm(request.POST)
       if form.is_valid():
           asset = form.save(commit=False)
           asset.created_date = timezone.now()
           asset.save()
           asset = asset.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/asset_list.html',
                         {'assets': asset})
   else:
       form = assetForm()
       # print("Else")
   return render(request, 'portfolio/asset_new.html', {'form': form})

@login_required
def asset_edit(request, pk):
    asset = get_object_or_404(asset, pk=pk)
    if request.method == "POST":
       form = assetForm(request.POST, instance=asset)
       if form.is_valid():
           asset = form.save()
           asset.updated_date = timezone.now()
           asset.save()
           asset = asset.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/asset_list.html', {'assets': asset})
    else:
       # print("else")
       form = assetForm(instance=asset)
    return render(request, 'portfolio/asset_edit.html', {'form': form})

@login_required
def asset_delete(request, pk):
   asset = get_object_or_404(asset, pk=pk)
   asset.delete()
   return redirect('portfolio:asset_list')

class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)

portfolio/templates/portfolio/asset_delete.html
 {% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=asset.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/asset_edit.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Asset</h1>
    <form method="POST" class="asset-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/asset_list.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Asset Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Asset Management, your Midwest Asset Management Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Asset Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Make</th>
                <th>Model</th>
                <th>Serial Number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Value</th>
                <th>Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for asset in assets %}
                <tr>
                    <td>{{ asset.customer }}</td>
                    <td>{{ asset.make }}</td>
                    <td>{{ asset.model }}</td>
                    <td>{{ asset.serial_number }}</td>
                    <td>{{ asset.category }}</td>
                    <td>{{ asset.description }}</td>
                    <td>{{ asset.value }}</td>
                    <td>{{ asset.date }}</td>
                    <td><a href="{% url 'portfolio:asset_edit' pk=asset.pk %}"
                           class="btn btn-warning">Edit</a></td>

                    <td><a href="{% url 'portfolio:asset_delete' pk=asset.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
         <a href="{% url 'portfolio:asset_new' %}" class="row"><span
                    class="btn btn-primary">Add Asset</span></a>
     </div>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/customer_edit.html
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
<!DOCTYPE html>
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
     <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Eagle Financial Services
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                <li><a href="{% url 'portfolio:customer_list' %}">Customers</a></li>
               <li><a href="{% url 'portfolio:asset_list' %}">Assets</a></li>
                <li><a href="{% url 'portfolio:misc_list' %}">Miscellaneous</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/investment_delete.html
 {% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=investment.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/investment_edit.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Investment</h1>
    <form method="POST" class="investment-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Investment Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
                <tr>
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date }}</td>
                     <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                           class="btn btn-warning">Edit</a></td>

                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
         <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                    class="btn btn-primary">Add Investment</span></a>
     </div>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/misc_delete.html
 {% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=misc.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/misc_edit.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Miscellaneous</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/misc_list.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Asset Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Asset Management, your Midwest Asset Management Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Miscellaneous Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer number</th>
                <th>make</th>
                <th>model</th>
                <th>name</th>
                <th>value</th>
                <th>category</th>
                <th>description</th>
                <th>date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for misc in miscs %}
                <tr>
                    <td>{{ misc.customer }}</td>
                    <td>{{ misc.make }}</td>
                    <td>{{ misc.model }}</td>
                    <td>{{ misc.name }}</td>
                    <td>{{ misc.value }}</td>
                    <td>{{ misc.category }}</td>
                    <td>{{ misc.description }}</td>
                    <td>{{ misc.date }}</td>
                    <td><a href="{% url 'portfolio:misc_edit' pk=misc.pk %}"
                           class="btn btn-warning">Edit</a></td>

                    <td><a href="{% url 'portfolio:misc_delete' pk=misc.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                 </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
            <a href="{% url 'portfolio:misc_new' %}" class="row"><span
                    class="btn btn-primary">Add Misc</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/misc_new.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Miscellaneous Asset</h1>
    <form method="POST" class="misc-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/stock_edit.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/stock_new.html
<!DOCTYPE html>
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}